# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0012_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
